name: Run CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  container_name:
    runs-on: ubuntu-latest
    steps:
      - name: Build frontend
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd 
            cd CI
            rm -rf frontend
            git clone https://github.com/parlamentaqui/frontend/
            cp envs/.env_tse frontend/.env
            cd frontend
            git checkout ${{ github.event.pull_request.head.ref }}
            npm install
            nohup npm run dev &
            sleep 15
            kill -9 $(lsof -t -i:3000)
          host: ${{ secrets.DO_HOST }}
          pass: ${{ secrets.DO_PASSWORD }}
